// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfKArS15NQaLbRgCFwkqglnnDvWIFaWeA',
    appId: '1:273189499139:web:21e4bdd6d9c24e4cbdb936',
    messagingSenderId: '273189499139',
    projectId: 'gift2grow-7cf1c',
    authDomain: 'gift2grow-7cf1c.firebaseapp.com',
    storageBucket: 'gift2grow-7cf1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_jY6hYtxXdM_GuwRtagb9qHMNbcxcfEM',
    appId: '1:273189499139:android:48d79e99eb4a4846bdb936',
    messagingSenderId: '273189499139',
    projectId: 'gift2grow-7cf1c',
    storageBucket: 'gift2grow-7cf1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClENv_ToDJdUaL04Zam2Nu2ox4PJXHxFY',
    appId: '1:273189499139:ios:b00582183a370116bdb936',
    messagingSenderId: '273189499139',
    projectId: 'gift2grow-7cf1c',
    storageBucket: 'gift2grow-7cf1c.appspot.com',
    iosBundleId: 'com.example.gift2grow',
  );
}
